### ISSUE TITLE
Duplicate key 'Drilldown Menu'

### ISSUE THREAD

**Issue by ghost** [GBratsos/atom-zurb-foundation#10]
With a fresh vanilla install of atom, after adding atom-zurb-foundation, I get the following error.  Sorry in advance if this is n00bish!
![screen shot 2018-04-08 at 7 16 48 pm](https://user-images.githubusercontent.com/24358542/38473663-d6c5d85e-3b61-11e8-9d35-d8198005057b.png)

**Comment by holaneph** [comment]
I had the same issue; Opened that components.cson file and I manually renamed the duplicated (line 278) to `'Drilldown Menu Scroll Top'`
and next, I have another duplicate key: `'Accordion Multi-expand'` (line 515) ... renamed to `' Accordion Multi-expand Closed'.`

Reloaded Atom and the package loads successfully. Yet to be tested that the altered snippets work...

**Comment by GBratsos** [comment]
Thanks for your contributions! We need to check and update the plugin in general because i think it's not with the latest ZURB Foundation components.

I'm trying to squeeze some time to update both of my plugins for Atom and Brackets.

Any help is really appreciated 👍

**Comment by GBratsos** [comment]
I just published an updated version fixing this problem. Check if there is any problem and re-open this issue.

Thanks again for your help.

**Comment by ghost** [comment]
Awesome Thanks!!!

I use the Zurb Template and am in a process of creating partials of each and every foundation 6 built in component to make UI/UX dev a snap by including them with the built in Handlebars.  That said, I’ll probably be pulling all of your snippets!  I’ll give you feedback as I go and will definitely help build it out!  Thanks for creating this!
