### ISSUE TITLE
Unable to use package

### ISSUE THREAD

**Issue by wjgo** [GBratsos/atom-zurb-foundation#8]
Atom 1.14.2 x64

I have installed the package but can not get anything to work.  I am new to Atom though.  I do have a grammar set, and other packages store.  This package is not listed in Package menu (or grammar), but says it is installed in settings window. I uninstalled it and used a command line to install, settings said it was there and enable but I still can't find a way.  Is there something I am missing?

**Comment by GBratsos** [comment]
Hello @wjgo ! I must take a look to the package because I haven't updated for a long time. Maybe try to install it via the command line.

**Comment by wjgo** [comment]
Hello - I was able to get it going.  Not sure what started it - but now its working. But not all things will show code, like float classes, flex video and many plugins.
